export default {
  GET_EXCEL_CATEGORY_REQUEST: 'GET_EXCEL_CATEGORY_REQUEST',
  GET_EXCEL_CATEGORY_SUCCESS: 'GET_EXCEL_CATEGORY_SUCCESS',
  GET_EXCEL_CATEGORY_FAILURE: 'GET_EXCEL_CATEGORY_FAILURE',
};
