export default {
  SELECT_FACILITY: 'SELECT_FACILITY',
  SELECT_ROOM: 'SELECT_ROOM',

  GET_FACILITY_INFO_REQUEST: 'GET_FACILITY_INFO_REQUEST',
  GET_FACILITY_INFO_SUCCESS: 'GET_FACILITY_INFO_SUCCESS',
  GET_FACILITY_INFO_FAILURE: 'GET_FACILITY_INFO_FAILURE',

  GET_FACILITIES_REQUEST: 'GET_FACILITIES_REQUEST',
  GET_FACILITIES_SUCCESS: 'GET_FACILITIES_SUCCESS',
  GET_FACILITIES_FAILURE: 'GET_FACILITIES_FAILURE',

  CREATE_FACILITY_REQUEST: 'CREATE_FACILITY_REQUEST',
  CREATE_FACILITY_SUCCESS: 'CREATE_FACILITY_SUCCESS',
  CREATE_FACILITY_FAILURE: 'CREATE_FACILITY_FAILURE',

  UPDATE_FACILITY_REQUEST: 'UPDATE_FACILITY_REQUEST',
  UPDATE_FACILITY_SUCCESS: 'UPDATE_FACILITY_SUCCESS',
  UPDATE_FACILITY_FAILURE: 'UPDATE_FACILITY_FAILURE',

  DELETE_FACILITY_REQUEST: 'DELETE_FACILITY_REQUEST',
  DELETE_FACILITY_SUCCESS: 'DELETE_FACILITY_SUCCESS',
  DELETE_FACILITY_FAILURE: 'DELETE_FACILITY_FAILURE',

  GET_ROOMS_REQUEST: 'GET_ROOMS_REQUEST',
  GET_ROOMS_SUCCESS: 'GET_ROOMS_SUCCESS',
  GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE',

  GET_AVAILABLE_ROOMS_REQUEST: 'GET_AVAILABLE_ROOMS_REQUEST',
  GET_AVAILABLE_ROOMS_SUCCESS: 'GET_AVAILABLE_ROOMS_SUCCESS',
  GET_AVAILABLE_ROOMS_FAILURE: 'GET_AVAILABLE_ROOMS_FAILURE',

  CREATE_ROOMS_REQUEST: 'CREATE_ROOMS_REQUEST',
  CREATE_ROOMS_SUCCESS: 'CREATE_ROOMS_SUCCESS',
  CREATE_ROOMS_FAILURE: 'CREATE_ROOMS_FAILURE',

  UPDATE_ROOM_REQUEST: 'UPDATE_ROOM_REQUEST',
  UPDATE_ROOM_SUCCESS: 'UPDATE_ROOM_SUCCESS',
  UPDATE_ROOM_FAILURE: 'UPDATE_ROOM_FAILURE',

  DELETE_ROOM_REQUEST: 'DELETE_ROOM_REQUEST',
  DELETE_ROOM_SUCCESS: 'DELETE_ROOM_SUCCESS',
  DELETE_ROOM_FAILURE: 'DELETE_ROOM_FAILURE',

  GET_WAITING_LIST_REQUEST: 'GET_WAITING_LIST_REQUEST',
  GET_WAITING_LIST_SUCCESS: 'GET_WAITING_LIST_SUCCESS',
  GET_WAITING_LIST_FAILURE: 'GET_WAITING_LIST_FAILURE',

  GET_WAITING_LIST_BY_FACILITY_REQUEST: 'GET_WAITING_LIST_BY_FACILITY_REQUEST',
  GET_WAITING_LIST_BY_FACILITY_SUCCESS: 'GET_WAITING_LIST_BY_FACILITY_SUCCESS',
  GET_WAITING_LIST_BY_FACILITY_FAILURE: 'GET_WAITING_LIST_BY_FACILITY_FAILURE',

  GET_IN_HOME_REQUEST: 'GET_IN_HOME_REQUEST',
  GET_IN_HOME_SUCCESS: 'GET_IN_HOME_SUCCESS',
  GET_IN_HOME_FAILURE: 'GET_IN_HOME_FAILURE',

  GET_IN_HOME_BY_FACILITY_REQUEST: 'GET_IN_HOME_BY_FACILITY_REQUEST',
  GET_IN_HOME_BY_FACILITY_SUCCESS: 'GET_IN_HOME_BY_FACILITY_SUCCESS',
  GET_IN_HOME_BY_FACILITY_FAILURE: 'GET_IN_HOME_BY_FACILITY_FAILURE',

  GET_IN_QUARANTINE_REQUEST: 'GET_IN_QUARANTINE_REQUEST',
  GET_IN_QUARANTINE_SUCCESS: 'GET_IN_QUARANTINE_SUCCESS',
  GET_IN_QUARANTINE_FAILURE: 'GET_IN_QUARANTINE_FAILURE',

  GET_IN_QUARANTINE_BY_FACILITY_REQUEST:
    'GET_IN_QUARANTINE_BY_FACILITY_REQUEST',
  GET_IN_QUARANTINE_BY_FACILITY_SUCCESS:
    'GET_IN_QUARANTINE_BY_FACILITY_SUCCESS',
  GET_IN_QUARANTINE_BY_FACILITY_FAILURE:
    'GET_IN_QUARANTINE_BY_FACILITY_FAILURE',

  GET_COMPLETED_REQUEST: 'GET_COMPLETED_REQUEST',
  GET_COMPLETED_SUCCESS: 'GET_COMPLETED_SUCCESS',
  GET_COMPLETED_FAILURE: 'GET_COMPLETED_FAILURE',

  GET_COMPLETED_BY_FACILITY_REQUEST: 'GET_COMPLETED_BY_FACILITY_REQUEST',
  GET_COMPLETED_BY_FACILITY_SUCCESS: 'GET_COMPLETED_BY_FACILITY_SUCCESS',
  GET_COMPLETED_BY_FACILITY_FAILURE: 'GET_COMPLETED_BY_FACILITY_FAILURE',

  GET_QUARANTINE_FORM_REQUEST: 'GET_QUARANTINE_FORM_REQUEST',
  GET_QUARANTINE_FORM_SUCCESS: 'GET_QUARANTINE_FORM_SUCCESS',
  GET_QUARANTINE_FORM_FAILURE: 'GET_QUARANTINE_FORM_FAILURE',

  GET_QUARANTINE_FORM_BY_FACILITY_REQUEST:
    'GET_QUARANTINE_FORM_BY_FACILITY_REQUEST',
  GET_QUARANTINE_FORM_BY_FACILITY_SUCCESS:
    'GET_QUARANTINE_FORM_BY_FACILITY_SUCCESS',
  GET_QUARANTINE_FORM_BY_FACILITY_FAILURE:
    'GET_QUARANTINE_FORM_BY_FACILITY_FAILURE',

  CREATE_QUARANTINE_FORM_REQUEST: 'CREATE_QUARANTINE_FORM_REQUEST',
  CREATE_QUARANTINE_FORM_SUCCESS: 'CREATE_QUARANTINE_FORM_SUCCESS',
  CREATE_QUARANTINE_FORM_FAILURE: 'CREATE_QUARANTINE_FORM_FAILURE',

  GET_QUARANTINE_FORM_DETAIL_REQUEST: 'GET_QUARANTINE_FORM_DETAIL_REQUEST',
  GET_QUARANTINE_FORM_DETAIL_SUCCESS: 'GET_QUARANTINE_FORM_DETAIL_SUCCESS',
  GET_QUARANTINE_FORM_DETAIL_FAILURE: 'GET_QUARANTINE_FORM_DETAIL_FAILURE',

  CREATE_APPOINT_REQUEST: 'CREATE_APPOINT_REQUEST',
  CREATE_APPOINT_SUCCESS: 'CREATE_APPOINT_SUCCESS',
  CREATE_APPOINT_FAILURE: 'CREATE_APPOINT_FAILURE',

  APPOINT_REQUEST: 'APPOINT_REQUEST',
  APPOINT_SUCCESS: 'APPOINT_SUCCESS',
  APPOINT_FAILURE: 'APPOINT_FAILURE',

  TAKE_IN_REQUEST: 'TAKE_IN_REQUEST',
  TAKE_IN_SUCCESS: 'TAKE_IN_SUCCESS',
  TAKE_IN_FAILURE: 'TAKE_IN_FAILURE',

  COMPLETE_FACILITY_REQUEST: 'COMPLETE_FACILITY_REQUEST',
  COMPLETE_FACILITY_SUCCESS: 'COMPLETE_FACILITY_SUCCESS',
  COMPLETE_FACILITY_FAILURE: 'COMPLETE_FACILITY_FAILURE',

  TRANSFER_FACILITY_REQUEST: 'TRANSFER_FACILITY_REQUEST',
  TRANSFER_FACILITY_SUCCESS: 'TRANSFER_FACILITY_SUCCESS',
  TRANSFER_FACILITY_FAILURE: 'TRANSFER_FACILITY_FAILURE',

  TRANSFER_TREATMENT_REQUEST: 'TRANSFER_TREATMENT_REQUEST',
  TRANSFER_TREATMENT_SUCCESS: 'TRANSFER_TREATMENT_SUCCESS',
  TRANSFER_TREATMENT_FAILURE: 'TRANSFER_TREATMENT_FAILURE',

  TRANSFER_ROOM_REQUEST: 'TRANSFER_ROOM_REQUEST',
  TRANSFER_ROOM_SUCCESS: 'TRANSFER_ROOM_SUCCESS',
  TRANSFER_ROOM_FAILURE: 'TRANSFER_ROOM_FAILURE',

  SET_MANAGER_REQUEST: 'SET_MANAGER_REQUEST',
  SET_MANAGER_SUCCESS: 'SET_MANAGER_SUCCESS',
  SET_MANAGER_FAILURE: 'SET_MANAGER_FAILURE',

  EXTEND_FACILITY_REQUEST: 'EXTEND_FACILITY_REQUEST',
  EXTEND_FACILITY_SUCCESS: 'EXTEND_FACILITY_SUCCESS',
  EXTEND_FACILITY_FAILURE: 'EXTEND_FACILITY_FAILURE',

  GET_HISTORIES_REQUEST: 'GET_HISTORIES_REQUEST',
  GET_HISTORIES_SUCCESS: 'GET_HISTORIES_SUCCESS',
  GET_HISTORIES_FAILURE: 'GET_HISTORIES_FAILURE',

  TOGGLE_ROOM_STATUS_REQUEST: 'TOGGLE_ROOM_STATUS_REQUEST',
  TOGGLE_ROOM_STATUS_SUCCESS: 'TOGGLE_ROOM_STATUS_SUCCESS',
  TOGGLE_ROOM_STATUS_FAILURE: 'TOGGLE_ROOM_STATUS_FAILURE',

  GET_QUARANTINE_STATISTIC_1_REQUEST: 'GET_QUARANTINE_STATISTIC_1_REQUEST',
  GET_QUARANTINE_STATISTIC_1_SUCCESS: 'GET_QUARANTINE_STATISTIC_1_SUCCESS',
  GET_QUARANTINE_STATISTIC_1_FAILURE: 'GET_QUARANTINE_STATISTIC_1_FAILURE',

  GET_QUARANTINE_STATISTIC_2_REQUEST: 'GET_QUARANTINE_STATISTIC_2_REQUEST',
  GET_QUARANTINE_STATISTIC_2_SUCCESS: 'GET_QUARANTINE_STATISTIC_2_SUCCESS',
  GET_QUARANTINE_STATISTIC_2_FAILURE: 'GET_QUARANTINE_STATISTIC_2_FAILURE',

  GET_QUARANTINE_STATISTIC_3_REQUEST: 'GET_QUARANTINE_STATISTIC_3_REQUEST',
  GET_QUARANTINE_STATISTIC_3_SUCCESS: 'GET_QUARANTINE_STATISTIC_3_SUCCESS',
  GET_QUARANTINE_STATISTIC_3_FAILURE: 'GET_QUARANTINE_STATISTIC_3_FAILURE',

  GET_QUARANTINE_STATISTIC_4_REQUEST: 'GET_QUARANTINE_STATISTIC_4_REQUEST',
  GET_QUARANTINE_STATISTIC_4_SUCCESS: 'GET_QUARANTINE_STATISTIC_4_SUCCESS',
  GET_QUARANTINE_STATISTIC_4_FAILURE: 'GET_QUARANTINE_STATISTIC_4_FAILURE',

  GET_QUARANTINE_STATISTIC_5_REQUEST: 'GET_QUARANTINE_STATISTIC_5_REQUEST',
  GET_QUARANTINE_STATISTIC_5_SUCCESS: 'GET_QUARANTINE_STATISTIC_5_SUCCESS',
  GET_QUARANTINE_STATISTIC_5_FAILURE: 'GET_QUARANTINE_STATISTIC_5_FAILURE',

  GET_QUARANTINE_STATISTIC_6_REQUEST: 'GET_QUARANTINE_STATISTIC_6_REQUEST',
  GET_QUARANTINE_STATISTIC_6_SUCCESS: 'GET_QUARANTINE_STATISTIC_6_SUCCESS',
  GET_QUARANTINE_STATISTIC_6_FAILURE: 'GET_QUARANTINE_STATISTIC_6_FAILURE',

  GET_QUARANTINE_STATISTIC_7_REQUEST: 'GET_QUARANTINE_STATISTIC_7_REQUEST',
  GET_QUARANTINE_STATISTIC_7_SUCCESS: 'GET_QUARANTINE_STATISTIC_7_SUCCESS',
  GET_QUARANTINE_STATISTIC_7_FAILURE: 'GET_QUARANTINE_STATISTIC_7_FAILURE',

  GET_QUARANTINE_STATISTIC_8_REQUEST: 'GET_QUARANTINE_STATISTIC_8_REQUEST',
  GET_QUARANTINE_STATISTIC_8_SUCCESS: 'GET_QUARANTINE_STATISTIC_8_SUCCESS',
  GET_QUARANTINE_STATISTIC_8_FAILURE: 'GET_QUARANTINE_STATISTIC_8_FAILURE',

  GET_QUARANTINE_STATISTIC_9_REQUEST: 'GET_QUARANTINE_STATISTIC_9_REQUEST',
  GET_QUARANTINE_STATISTIC_9_SUCCESS: 'GET_QUARANTINE_STATISTIC_9_SUCCESS',
  GET_QUARANTINE_STATISTIC_9_FAILURE: 'GET_QUARANTINE_STATISTIC_9_FAILURE',
};
