export default {
  //LẤY THEO ID ?
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  // LẤY DANH SÁCH
  GET_PROFILES_REQUEST: "GET_PROFILES_REQUEST",
  GET_PROFILES_SUCCESS: "GET_PROFILES_SUCCESS",
  GET_PROFILES_FAILURE: "GET_PROFILES_FAILURE",

  CREATE_PROFILE_REQUEST: "CREATE_PROFILE_REQUEST",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",

  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
};
